### ISSUE TITLE
Exception Error with this  msg: '''dict object'' has no attribute ''priority,name'''

### ISSUE THREAD

**Issue by m-amir-ir** [devture/com.devture.ansible.role.systemd_service_manager#2]
Hello every one , I noticed this error when I ran your ansible code on my ansible code from ansible-galaxy .

then I got this error related to below part of code:
```
- when: devture_systemd_service_manager_service_restart_mode == 'clean-stop-start'
  block:
    - name: Ensure systemd services are stopped
      ansible.builtin.service:
        name: "{{ item.name }}"
        state: stopped
      with_items: "{{ devture_systemd_service_manager_services_list_to_work_with | sort (attribute='priority,name', reverse=true) }}"
      when: not ansible_check_mode

    - name: Ensure systemd services are started
      ansible.builtin.service:
        name: "{{ item.name }}"
        state: started
        enabled: "{{ devture_systemd_service_manager_services_autostart_enabled }}"
      with_items: "{{ devture_systemd_service_manager_services_list_to_work_with | sort (attribute='priority,name') }}"
      when: not ansible_check_mode

- when: devture_systemd_service_manager_service_restart_mode == 'one-by-one'
  block:
    - name: Ensure systemd services are restarted one by one
      ansible.builtin.service:
        name: "{{ item.name }}"
        state: restarted
        enabled: "{{ devture_systemd_service_manager_services_autostart_enabled }}"
      with_items: "{{ devture_systemd_service_manager_services_list_to_work_with | sort (attribute='priority,name') }}"
      when: not ansible_check_mode
```

I changed your code  to below code and after that it worked out. 

```
- name: Ensure systemd services are stopped
      ansible.builtin.service:
        name: "{{ item.name }}"
        state: stopped
      #with_items: "{{ devture_systemd_service_manager_services_list_to_work_with  }}"
      with_items: "{{ devture_systemd_service_manager_services_list_to_work_with | sort (attribute='priority', reverse=true) | sort (attribute='name', reverse=true) }}"
      when: not ansible_check_mode

    - name: Ensure systemd services are started
      ansible.builtin.service:
        name: "{{ item.name }}"
        state: started
        enabled: "{{ devture_systemd_service_manager_services_autostart_enabled }}"
      #with_items: "{{ devture_systemd_service_manager_services_list_to_work_with  }}"
      with_items: "{{ devture_systemd_service_manager_services_list_to_work_with  | sort (attribute='priority') | sort (attribute='name') }}"
      when: not ansible_check_mode

- when: devture_systemd_service_manager_service_restart_mode == 'one-by-one'
  block:
    - name: Ensure systemd services are restarted one by one
      ansible.builtin.service:
        name: "{{ item.name }}"
        state: restarted
        enabled: "{{ devture_systemd_service_manager_services_autostart_enabled }}"
      #with_items: "{{ devture_systemd_service_manager_services_list_to_work_with  }}"
      with_items: "{{ devture_systemd_service_manager_services_list_to_work_with | sort (attribute='priority') | sort (attribute='name') }}"
      when: not ansible_check_mode


```
if you could consider this new part for your next update , I would be grateful. 

Thanks.
